[tox]
minversion = 2.5.0
isolated_build = True
envlist = qc.sty,qc.cov,qc.sec,py37,py36
skipsdist = True

[testenv]
install_command = pip install -U {opts} {packages}
commands = pytest --numprocesses=auto --dist=loadscope {posargs}
setenv =
   OS_TEST_TIMEOUT=240
deps = -r{toxinidir}/test-requirements.txt

[testenv:qc.cov]
commands = pytest --cov=demo_advanced --cov-report=html dogs_breed_det/tests

[testenv:qc.sec]
commands = bandit -r dogs_breed_det -x tests

[testenv:qc.sty]
commands = 
   - flake8 --output-file=flake8.log \
   --format=pylint dogs_breed_det
