# .sqa/config.yml - jenkins-pipeline-library configuration file
sqa_criteria:
  QC.Sty:
    repos:
      dogs_breed_det:
        container: dogs-testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sty
  QC.Uni:
    repos:
      dogs_breed_det:
        container: dogs-testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.cov
  QC.Sec:
    repos:
      dogs_breed_det:
        container: dogs-testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sec

environment:
  LANG: C.UTF-8

timeout: 600